stop:
  description: Stop the WebSocket connection to the EdgeOS device

restart:
  description: Restart the WebSocket connection to the EdgeOS device

save_debug_data:
  description: "Store the EdgeOS state to file, Path in CONFIG_PATH/edgeos_data.log"
